import { useState } from "react";
import { Send, MessageCircle } from "lucide-react";
import { Button } from "./ui/button";

const responses: Record<string, string> = {
  hungry: "🍱 Great news! There's a cafe 3 min walk away with 5 unsold wraps. Use code NOURISH3 for free pickup. Expires in 25 min!",
  food: "🥗 I found 2 nearby spots with surplus food. Reply '1' for Bakery Lane (sandwiches) or '2' for Green Grocer (fruit boxes).",
  help: "I can help you find free surplus meals nearby, report food waste, or connect with local food banks. Just say 'hungry' to start!",
};

const defaultResponse = "I understand! Try saying 'hungry', 'food', or 'help' and I'll assist you with finding nearby surplus meals.";

const DemoChat = () => {
  const [messages, setMessages] = useState<{ from: "bot" | "user"; text: string }[]>([
    { from: "bot", text: "Hello! I'm your food rescue assistant. Send a message to start." },
  ]);
  const [input, setInput] = useState("");

  const send = () => {
    if (!input.trim()) return;
    const userMsg = input.trim();
    setInput("");
    const key = userMsg.toLowerCase();
    const reply = responses[key] || defaultResponse;
    setMessages((m) => [...m, { from: "user" as const, text: userMsg }]);
    setTimeout(() => setMessages((m) => [...m, { from: "bot" as const, text: reply }]), 600);
  };

  return (
    <section id="demo" className="container mx-auto my-16">
      <div className="bg-card rounded-4xl p-8 md:p-12 shadow-lg flex flex-wrap gap-10">
        <div className="flex-1 min-w-[280px]">
          <h3 className="text-2xl md:text-3xl font-bold text-foreground mb-4">Try NourishNet yourself</h3>
          <p className="text-muted-foreground mb-4">
            This chat simulates how a user interacts with our agent on WhatsApp. Type <strong>"hungry"</strong>, <strong>"food"</strong>, or <strong>"help"</strong> to see the agent in action.
          </p>
          <p className="text-sm text-muted-foreground">⚡ Powered by FLock API (Llama 3) for intent recognition and safety.</p>
          <div className="mt-4 bg-secondary rounded-xl px-4 py-3 text-sm text-secondary-foreground">
            📱 Multi-channel ready: WhatsApp, Telegram, and SMS.
          </div>
        </div>
        <div className="flex-1 min-w-[280px] bg-secondary/50 rounded-3xl p-5">
          <div className="flex items-center gap-2 border-b border-border pb-3 mb-4">
            <MessageCircle className="h-5 w-5 text-primary" />
            <span className="font-semibold text-foreground text-sm">NourishNet Simulator</span>
          </div>
          <div className="space-y-3 max-h-[260px] overflow-y-auto mb-4">
            {messages.map((m, i) => (
              <div
                key={i}
                className={
                  m.from === "bot"
                    ? "bg-secondary rounded-2xl rounded-bl-sm px-4 py-3 max-w-[85%] text-sm text-secondary-foreground"
                    : "bg-primary text-primary-foreground rounded-2xl rounded-br-sm px-4 py-3 max-w-[85%] ml-auto text-sm"
                }
              >
                {m.text}
              </div>
            ))}
          </div>
          <div className="flex gap-2">
            <input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && send()}
              placeholder="Type 'hungry'..."
              className="flex-1 px-4 py-2.5 rounded-full border border-border bg-card text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-ring"
            />
            <Button size="icon" onClick={send}>
              <Send className="h-4 w-4" />
            </Button>
          </div>
          <p className="text-xs text-muted-foreground text-center mt-3">Responses are generated by a simulated agent using FLock prompt chain.</p>
        </div>
      </div>
    </section>
  );
};

export default DemoChat;
